# Generated by Django 6.1.1 on 2026-09-13 20:54

import tenant.models.company
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier. Generated from the name when left blank.', max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, help_text='Registered legal entity, if it differs from the display name.', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[tenant.models.company.validate_timezone])),
                ('plan', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='standard', max_length=20)),
                ('onboarded_at', models.DateTimeField(blank=True, help_text='When the tenant went live - distinct from created_at.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to take a tenant out of service without deleting data.')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
