# Generated by Django 6.1.1 on 2026-09-17 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('father_husband_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('cnic_number', models.CharField(blank=True, max_length=20)),
                ('cnic_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=30)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location_area', models.CharField(blank=True, max_length=100)),
                ('sub_location', models.CharField(blank=True, max_length=100)),
                ('complete_address', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('business_address', models.TextField(blank=True)),
                ('business_contact_number', models.CharField(blank=True, max_length=20)),
                ('customer_source', models.CharField(blank=True, max_length=50)),
                ('referred_by', models.CharField(blank=True, max_length=255)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=30)),
                ('preferred_language', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], default='NEW', max_length=10)),
                ('record_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('marketing_contact_permission', models.CharField(blank=True, max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20)),
                ('family_group_reference', models.CharField(blank=True, max_length=255)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='customers', to='customers.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'phone'], name='customers_c_company_e97128_idx')],
            },
        ),
    ]
