# Generated by Django 6.1.1 on 2026-09-21 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0003_company_address_line1_company_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('HOTEL', 'Hotel'), ('FLIGHT', 'Flight'), ('TRANSPORT', 'Transport')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('meal_plan', models.CharField(blank=True, choices=[('ROOM_ONLY', 'Room Only'), ('BREAKFAST', 'Breakfast'), ('HALF_BOARD', 'Half Board'), ('FULL_BOARD', 'Full Board')], max_length=20)),
                ('nights', models.PositiveIntegerField(blank=True, null=True)),
                ('cabin_class', models.CharField(blank=True, choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=20)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.packagetemplate')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package template line',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'HOTEL'), models.Q(('city', ''), _negated=True), models.Q(('room_type', ''), _negated=True), models.Q(('meal_plan', ''), _negated=True), models.Q(('nights__isnull', True), _negated=True), ('cabin_class', ''), ('route', ''), ('vehicle_type', '')), models.Q(('kind', 'FLIGHT'), ('city', ''), ('room_type', ''), ('meal_plan', ''), ('nights__isnull', True), models.Q(('cabin_class', ''), _negated=True), models.Q(('route', ''), _negated=True), ('vehicle_type', '')), models.Q(('kind', 'TRANSPORT'), ('city', ''), ('room_type', ''), ('meal_plan', ''), ('nights__isnull', True), ('cabin_class', ''), ('route', ''), models.Q(('vehicle_type', ''), _negated=True)), _connector='OR'), name='spec_line_fields_match_kind')],
            },
        ),
    ]
