# Generated by Django 6.1.1 on 2026-09-19 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyVisaCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_country', models.CharField(max_length=100)),
                ('case_open_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('service_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PKR', max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('study_level', models.CharField(choices=[('DIPLOMA', 'Diploma'), ('FOUNDATION', 'Foundation'), ('BACHELORS', "Bachelor's"), ('MASTERS', "Master's"), ('PHD', 'PhD'), ('SCHOOL_COLLEGE', 'School / College'), ('OTHER', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(max_length=255)),
                ('preferred_intake', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('institution_application_status', models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('CONDITIONAL_OFFER', 'Conditional Offer'), ('UNCONDITIONAL_OFFER', 'Unconditional Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DEFERRED', 'Deferred')], default='NOT_APPLIED', max_length=20)),
                ('institution_reference', models.CharField(blank=True, max_length=100)),
                ('offer_acceptance_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONDITIONAL', 'Conditional'), ('UNCONDITIONAL', 'Unconditional'), ('ACCEPTED', 'Accepted'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=15)),
                ('course_start_date', models.DateField(blank=True, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tuition_deposit_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=255)),
                ('english_test_type', models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('PTE', 'PTE'), ('TOEFL', 'TOEFL'), ('OTHER', 'Other')], max_length=10)),
                ('english_test_score', models.CharField(blank=True, max_length=20)),
                ('academic_documents_status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete'), ('VERIFIED', 'Verified'), ('SUBMITTED', 'Submitted')], default='INCOMPLETE', max_length=15)),
                ('sop_status', models.CharField(blank=True, choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('FINAL', 'Final'), ('SUBMITTED', 'Submitted')], max_length=15)),
                ('financial_evidence_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete'), ('SUBMITTED', 'Submitted'), ('NOT_REQUIRED', 'Not Required')], default='NOT_STARTED', max_length=15)),
                ('enrolment_reference_type', models.CharField(blank=True, choices=[('CAS', 'CAS (UK)'), ('COE', 'CoE (Australia)'), ('I20', 'I-20 (USA)'), ('LOA', 'LOA (Canada)'), ('OTHER', 'Other')], max_length=10)),
                ('enrolment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('NOT_READY', 'Not Ready'), ('READY_TO_APPLY', 'Ready to Apply'), ('SUBMITTED', 'Submitted'), ('BIOMETRICS', 'Biometrics'), ('IN_PROCESS', 'In Process'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('CLOSED', 'Closed')], default='NOT_READY', max_length=20)),
                ('visa_tracking_reference', models.CharField(blank=True, max_length=100)),
                ('visa_application_date', models.DateField(blank=True, null=True)),
                ('biometrics_status', models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('BOOKED', 'Appointment Booked'), ('COMPLETED', 'Completed')], max_length=15)),
                ('medical_tb_status', models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], max_length=15)),
                ('visa_decision', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('WITHDRAWN', 'Withdrawn'), ('DEFERRED', 'Deferred'), ('OTHER', 'Other')], max_length=15)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_counselor', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisaConsultancyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_country', models.CharField(max_length=100)),
                ('case_open_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('service_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PKR', max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('visa_category', models.CharField(choices=[('VISIT_TOURIST', 'Visit / Tourist'), ('BUSINESS', 'Business'), ('FAMILY', 'Family'), ('TRANSIT', 'Transit'), ('WORK', 'Work'), ('OTHER', 'Other')], max_length=20)),
                ('purpose_of_travel', models.CharField(blank=True, max_length=255)),
                ('intended_travel_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('READY_TO_APPLY', 'Ready to Apply'), ('SUBMITTED', 'Submitted'), ('IN_PROCESS', 'In Process'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('CLOSED', 'Closed')], default='CONSULTATION', max_length=20)),
                ('embassy_vac', models.CharField(blank=True, max_length=255)),
                ('application_tracking_reference', models.CharField(blank=True, max_length=100)),
                ('application_submission_date', models.DateField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('biometrics_status', models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('BOOKED', 'Appointment Booked'), ('COMPLETED', 'Completed')], max_length=15)),
                ('document_checklist_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete'), ('SUBMITTED', 'Submitted')], default='NOT_STARTED', max_length=15)),
                ('visa_decision', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('WITHDRAWN', 'Withdrawn'), ('DEFERRED', 'Deferred'), ('OTHER', 'Other')], max_length=15)),
                ('visa_valid_from', models.DateField(blank=True, null=True)),
                ('visa_valid_until', models.DateField(blank=True, null=True)),
                ('passport_collection_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('READY', 'Ready for Collection'), ('COLLECTED', 'Collected'), ('COURIERED', 'Couriered')], max_length=15)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_counselor', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
