# Generated by Django 6.1.1 on 2026-09-21 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0002_customer_avatar'),
        ('tenant', '0003_company_address_line1_company_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='lead_guest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketingbooking',
            name='pnr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transportbooking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='hotelbooking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['CONFIRMED', 'COMPLETED']), _negated=True), models.Q(('lead_guest_name', ''), _negated=True), _connector='OR'), name='hotel_lead_guest_required_once_confirmed'),
        ),
        migrations.AddConstraint(
            model_name='ticketingbooking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['ISSUED', 'REISSUED']), _negated=True), models.Q(('pnr', ''), _negated=True), _connector='OR'), name='ticketing_pnr_required_once_issued'),
        ),
        migrations.AddConstraint(
            model_name='transportbooking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['DRIVER_ASSIGNED', 'COMPLETED']), _negated=True), ('pickup_time__isnull', False), _connector='OR'), name='transport_pickup_time_required_once_assigned'),
        ),
    ]
