# Generated by Django 6.1.1 on 2026-09-21 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_package_links(apps, schema_editor):
    """Move the old many-to-many rows onto PackageComponent before they are dropped."""
    Package = apps.get_model('bookings', 'Package')
    PackageComponent = apps.get_model('bookings', 'PackageComponent')
    links = (
        ('hotels', 'hotel_booking_id'),
        ('tickets', 'ticketing_booking_id'),
        ('transports', 'transport_booking_id'),
    )
    for package in Package.objects.all().iterator():
        for accessor, column in links:
            booking_ids = getattr(package, accessor).values_list('pk', flat=True)
            for booking_id in booking_ids:
                PackageComponent.objects.create(
                    company_id=package.company_id,
                    package_id=package.pk,
                    **{column: booking_id},
                )


def restore_package_links(apps, schema_editor):
    Package = apps.get_model('bookings', 'Package')
    PackageComponent = apps.get_model('bookings', 'PackageComponent')
    for component in PackageComponent.objects.all().iterator():
        package = Package.objects.get(pk=component.package_id)
        if component.hotel_booking_id:
            package.hotels.add(component.hotel_booking_id)
        elif component.ticketing_booking_id:
            package.tickets.add(component.ticketing_booking_id)
        elif component.transport_booking_id:
            package.transports.add(component.transport_booking_id)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_package_layers'),
        ('catalog', '0001_package_layers'),
        ('tenant', '0003_company_address_line1_company_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='catalog.packagetemplate'),
        ),
        migrations.AlterField(
            model_name='hajjbooking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hajj_trips', to='bookings.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text="Label for this booked bundle, e.g. 'Family of 4 — Hajj July 2026'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_trips', to='bookings.package'),
        ),
        migrations.AlterField(
            model_name='umrahbooking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umrah_trips', to='bookings.package'),
        ),
        migrations.AddField(
            model_name='packagecomponent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company'),
        ),
        migrations.AddField(
            model_name='packagecomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagecomponent',
            name='hotel_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_components', to='bookings.hotelbooking'),
        ),
        migrations.AddField(
            model_name='packagecomponent',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bookings.package'),
        ),
        migrations.AddField(
            model_name='packagecomponent',
            name='ticketing_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_components', to='bookings.ticketingbooking'),
        ),
        migrations.AddField(
            model_name='packagecomponent',
            name='transport_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_components', to='bookings.transportbooking'),
        ),
        migrations.AddField(
            model_name='packagecomponent',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='packagecomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hotel_booking__isnull', False), ('ticketing_booking__isnull', True), ('transport_booking__isnull', True)), models.Q(('hotel_booking__isnull', True), ('ticketing_booking__isnull', False), ('transport_booking__isnull', True)), models.Q(('hotel_booking__isnull', True), ('ticketing_booking__isnull', True), ('transport_booking__isnull', False)), _connector='OR'), name='exactly_one_component_type_set'),
        ),
        migrations.AddConstraint(
            model_name='packagecomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('hotel_booking__isnull', False)), fields=('package', 'hotel_booking'), name='uniq_package_hotel_booking'),
        ),
        migrations.AddConstraint(
            model_name='packagecomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('ticketing_booking__isnull', False)), fields=('package', 'ticketing_booking'), name='uniq_package_ticketing_booking'),
        ),
        migrations.AddConstraint(
            model_name='packagecomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('transport_booking__isnull', False)), fields=('package', 'transport_booking'), name='uniq_package_transport_booking'),
        ),
        migrations.RunPython(copy_package_links, restore_package_links),
        migrations.RemoveField(
            model_name='package',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='package',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='package',
            name='transports',
        ),
    ]
