# Generated by Django 6.1.1 on 2026-09-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_package_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjbooking',
            name='application_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
