# Generated by Django 6.1.1 on 2026-09-21 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_avatar'),
        ('tenant', '0003_company_address_line1_company_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_number', models.CharField(blank=True, db_index=True, help_text='LCCI membership number — the dedup key across sheets.', max_length=50)),
                ('membership_type', models.CharField(blank=True, help_text='Membership type from the source file (e.g. A = Annual, C = Corporate).', max_length=5)),
                ('company_name', models.CharField(max_length=500)),
                ('contact_person', models.CharField(blank=True, help_text='Contact name and designation as listed (e.g. "MR. ALI RAZA - Partner").', max_length=500)),
                ('business_sector', models.CharField(blank=True, help_text='Top-level sector from the section header (e.g. "AGRICULTURE & HORTICULTURE").', max_length=255)),
                ('sub_sector', models.CharField(blank=True, help_text='Sub-sector from the data row (e.g. "AGRICULTURAL CROPS & SEEDS").', max_length=255)),
                ('product_line', models.CharField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('converted_at', models.DateTimeField(blank=True, help_text='When the conversion happened.', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('converted_customer', models.ForeignKey(blank=True, help_text='Set when staff convert this directory entry into a Customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_entries', to='customers.customer')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryBusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(help_text='Source sheet name (e.g. "Manufacturers", "Exporters").', max_length=50)),
                ('sr_no', models.PositiveIntegerField(blank=True, help_text='Sequence number within the source sheet.', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('directory_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='directory.directorycompany')),
            ],
            options={
                'ordering': ['sheet_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='directory-imports/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('companies_created', models.PositiveIntegerField(default=0)),
                ('companies_updated', models.PositiveIntegerField(default=0)),
                ('activities_created', models.PositiveIntegerField(default=0)),
                ('issues_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_imports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(max_length=50)),
                ('row_number', models.PositiveIntegerField()),
                ('membership_number', models.CharField(blank=True, max_length=50)),
                ('field_name', models.CharField(blank=True, help_text='Which field the issue relates to, if applicable.', max_length=100)),
                ('issue_type', models.CharField(help_text='Machine-readable category (e.g. "missing_membership", "invalid_email").', max_length=50)),
                ('raw_value', models.TextField(blank=True, help_text='The original value from the file, for audit.')),
                ('message', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='directory.importbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenant.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='directorycompany',
            index=models.Index(fields=['company_name'], name='directory_d_company_335f98_idx'),
        ),
        migrations.AddIndex(
            model_name='directorycompany',
            index=models.Index(fields=['business_sector'], name='directory_d_busines_f0a0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='directorycompany',
            index=models.Index(fields=['sub_sector'], name='directory_d_sub_sec_8392b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorybusinessactivity',
            unique_together={('directory_company', 'sheet_name')},
        ),
        migrations.AddIndex(
            model_name='importrowissue',
            index=models.Index(fields=['batch', 'issue_type'], name='directory_i_batch_i_23382a_idx'),
        ),
    ]
